version: '3'
services:
  composer:
    image: composer:2.0
    environment:
      - COMPOSER_CACHE_DIR=/app/cache
    volumes:
      - .:/app
    restart: never
  php:
    image: php:7.4-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
  phpunit:
    image: php:7.4-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app/tests
    entrypoint: ../vendor/bin/phpunit
